### ISSUE TITLE
Update Helios base to OmniOS r151046 LTS

### ISSUE THREAD

**Issue by citrus-it** [oxidecomputer/helios#91]
Helios is currently based on OmniOS r151038 LTS which is supported up to 2024-05-04.
Prior to that, we should re-base helios on OmniOS r151046 LTS, supported up to 2026-05-01.

To give an idea of the scope, here are the differences in packages between the two LTS releases, using OmniOS' `pkgmgr` tool:

```
build% pkgmgr diff r151038 --dst r151046 --dst
```

| Package | Old Version | New Version |
| :------ | :---------- | :---------- |
| compress/lz4 | 1.9.3 | 1.9.4
| **compress/lzip** | _New_ | 1.23
| compress/xz | 5.2.6 | 5.4.2
| data/iso-codes | 4.6.0 | 4.13.0
| database/sqlite-3 | 3.35.5 | 3.41.2
| developer/build/automake | 1.16.3 | 1.16.5
| developer/build/gnu-make | 4.3 | 4.4.1
| developer/dtrace/toolkit | 0.99 | 0.99.20220214
| **developer/gcc11** | _New_ | 11.3.0
| **developer/gcc12** | _New_ | 12.2.0
| ~~developer/gcc44~~ | 4.4.4 | _Removed_
| ~~developer/gcc44/libgmp-gcc44~~ | 5.0.2 | _Removed_
| ~~developer/gcc44/libmpc-gcc44~~ | 0.8.2 | _Removed_
| ~~developer/gcc44/libmpfr-gcc44~~ | 3.1.0 | _Removed_
| ~~developer/gcc9~~ | 9.3.0 | _Removed_
| developer/gnu-binutils | 2.36.1 | 2.40
| developer/macro/cpp | 0.5.11 | 20220808
| developer/macro/gnu-m4 | 1.4.18 | 1.4.19
| developer/nasm | 2.15.5 | 2.16.1
| developer/parser/bison | 3.7.6 | 3.8.2
| developer/swig | 4.0.2 | 4.1.1
| ~~developer/tnf~~ | 0.5.11 | _Removed_
| developer/versioning/git | 2.31.8 | 2.40.1
| developer/versioning/mercurial | 5.7.1 | 6.3.3
| **driver/storage/smrt** | _New_ | 0.5.11
| **driver/storage/vio9p** | _New_ | 0.5.11
| **driver/storage/vioscsi** | _New_ | 0.5.11
| editor/vim | 8.2.4691 | 9.0.1443
| file/gnu-coreutils | 8.32 | 9.3
| file/gnu-findutils | 4.8.0 | 4.9.0
| library/c++/sigcpp | 3.0.6 | 3.4.0
| library/expat | 2.4.9 | 2.5.0
| library/glib2 | 2.68.1 | 2.74.6
| library/libffi | 3.3 | 3.4.4
| library/libidn | 1.36 | 1.41
| **library/lzlib** | _New_ | 1.13
| library/mpc | 1.2.1 | 1.3.1
| library/mpfr | 4.1.0 | 4.2.0
| library/ncurses | 6.2 | 6.4
| library/nghttp2 | 1.43.0 | 1.52.0
| library/nspr | 4.30 | 4.35
| library/nspr/header-nspr | 4.30 | 4.35
| library/pcre | 8.44 | 8.45
| library/pcre2 | 10.36 | 10.42
| **library/python-3/asn1crypto-311** | _New_ | 1.5.1
| ~~library/python-3/asn1crypto-39~~ | 1.4.0 | _Removed_
| **library/python-3/attrs-311** | _New_ | 22.2.0
| ~~library/python-3/attrs-39~~ | 20.3.0 | _Removed_
| **library/python-3/cffi-311** | _New_ | 1.15.1
| ~~library/python-3/cffi-39~~ | 1.14.5 | _Removed_
| ~~library/python-3/cheroot-39~~ | 8.5.2 | _Removed_
| ~~library/python-3/cherrypy-39~~ | 18.6.0 | _Removed_
| **library/python-3/coverage-311** | _New_ | 7.2.2
| ~~library/python-3/coverage-39~~ | 5.5 | _Removed_
| **library/python-3/crossenv-311** | _New_ | 1.4.0
| **library/python-3/cryptography-311** | _New_ | 39.0.2
| ~~library/python-3/cryptography-39~~ | 3.4.6 | _Removed_
| **library/python-3/idna-311** | _New_ | 3.4
| ~~library/python-3/idna-39~~ | 3.1 | _Removed_
| ~~library/python-3/jaraco-39~~ | 1.0.0 | _Removed_
| **library/python-3/js-regex-311** | _New_ | 1.0.1
| ~~library/python-3/js-regex-39~~ | 1.0.1 | _Removed_
| **library/python-3/jsonrpclib-311** | _New_ | 0.4.3.2
| ~~library/python-3/jsonrpclib-39~~ | 0.4.2 | _Removed_
| **library/python-3/jsonschema-311** | _New_ | 4.17.3
| ~~library/python-3/jsonschema-39~~ | 3.2.0 | _Removed_
| ~~library/python-3/mako-39~~ | 1.1.4 | _Removed_
| **library/python-3/meson-311** | _New_ | 1.0.1
| ~~library/python-3/meson-39~~ | 0.57.1 | _Removed_
| ~~library/python-3/more-itertools-39~~ | 8.7.0 | _Removed_
| **library/python-3/orjson-311** | _New_ | 3.8.8
| ~~library/python-3/orjson-39~~ | 3.5.1 | _Removed_
| **library/python-3/pip-311** | _New_ | 23.0.1
| ~~library/python-3/pip-39~~ | 21.0.1 | _Removed_
| ~~library/python-3/ply-39~~ | 3.11 | _Removed_
| ~~library/python-3/portend-39~~ | 2.7.1 | _Removed_
| ~~library/python-3/prettytable-39~~ | 2.1.0 | _Removed_
| ~~library/python-3/pybonjour-39~~ | 1.1.1 | _Removed_
| **library/python-3/pycodestyle-311** | _New_ | 2.10.0
| ~~library/python-3/pycodestyle-39~~ | 2.7.0 | _Removed_
| **library/python-3/pycparser-311** | _New_ | 2.21
| ~~library/python-3/pycparser-39~~ | 2.20 | _Removed_
| **library/python-3/pycurl-311** | _New_ | 7.44.1
| ~~library/python-3/pycurl-39~~ | 7.43.0.6 | _Removed_
| **library/python-3/pyopenssl-311** | _New_ | 23.0.0
| ~~library/python-3/pyopenssl-39~~ | 20.0.1 | _Removed_
| **library/python-3/pyrsistent-311** | _New_ | 0.19.3
| ~~library/python-3/pyrsistent-39~~ | 0.17.3 | _Removed_
| ~~library/python-3/pytz-39~~ | 2021.1 | _Removed_
| **library/python-3/pyyaml-311** | _New_ | 6.0
| ~~library/python-3/pyyaml-39~~ | 5.4.1 | _Removed_
| **library/python-3/rapidjson-311** | _New_ | 1.10
| ~~library/python-3/rapidjson-39~~ | 1.4 | _Removed_
| **library/python-3/semantic-version-311** | _New_ | 2.10.0
| ~~library/python-3/semantic-version-39~~ | 2.8.5 | _Removed_
| **library/python-3/setuptools-311** | _New_ | 67.6.0
| ~~library/python-3/setuptools-39~~ | 54.1.2 | _Removed_
| **library/python-3/setuptools-rust-311** | _New_ | 1.5.2
| ~~library/python-3/setuptools-rust-39~~ | 0.12.1 | _Removed_
| **library/python-3/six-311** | _New_ | 1.16.0
| ~~library/python-3/six-39~~ | 1.15.0 | _Removed_
| ~~library/python-3/tempora-39~~ | 4.0.1 | _Removed_
| **library/python-3/tomli-311** | _New_ | 2.0.1
| **library/python-3/typing-extensions-311** | _New_ | 4.5.0
| ~~library/python-3/wcwidth-39~~ | 0.2.5 | _Removed_
| ~~library/python-3/zc.lockfile-39~~ | 2.0 | _Removed_
| library/readline | 8.1 | 8.2
| **library/security/openssl-3** | _New_ | 3.0.9
| library/unixodbc | 2.3.9 | 2.3.11
| ~~media/cdrtools~~ | 3.1 | _Removed_
| **media/xorriso** | _New_ | 1.5.4.2
| network/dns/bind | 9.16.13 | 9.18.14
| network/openssh | 8.5.1 | 9.3.1
| network/openssh-server | 8.5.1 | 9.3.1
| network/rsync | 3.2.3 | 3.2.7
| network/service/isc-dhcp | 4.4.2.1 | 4.4.3.1
| **network/snoop** | _New_ | 0.5.11
| network/socat | 1.7.4.1 | 1.7.4.4
| **runtime/java/jexec** | _New_ | 0.5.11
| **runtime/java/openjdk17** | _New_ | 17.0.7
| runtime/perl | 5.32.1 | 5.36.1
| **runtime/python-311** | _New_ | 3.11.3
| ~~runtime/python-39~~ | 3.9.15 | _Removed_
| security/sudo | 1.9.12.2 | 1.9.13.3
| service/network/chrony | 4.1 | 4.3
| service/network/ntpsec | 1.2.0 | 1.2.2
| ~~service/network/slp~~ | 0.5.11 | _Removed_
| shell/bash | 5.1.4 | 5.2.15
| shell/pipe-viewer | 1.6.6 | 1.6.20
| shell/tcsh | 6.22.3 | 6.24.7
| shell/zsh | 5.8 | 5.9
| system/bhyve/firmware | 20210302 | 20230201
| system/data/hardware-registry | 2021.12.23 | 2023.2.23
| system/data/urxvt-terminfo | 9.22 | 9.31
| ~~system/kernel/dtrace/providers/xdt~~ | 0.5.11 | _Removed_
| system/library/dbus | 1.12.20 | 1.14.6
| system/library/g++-runtime | 10 | 12
| system/library/gcc-runtime | 10 | 12
| system/library/gccgo-runtime | 10 | 11
| system/library/gfortran-runtime | 10 | 12
| system/library/gobjc-runtime | 10 | 12
| system/library/libdbus | 1.12.20 | 1.14.6
| system/library/libdbus-glib | 0.110 | 0.112
| system/library/mozilla-nss | 3.63 | 3.89
| system/library/mozilla-nss/header-nss | 3.63 | 3.89
| system/library/pcap | 1.10.0 | 1.10.3
| ~~system/library/processor~~ | 0.5.11 | _Removed_
| **system/library/python/libbe-311** | _New_ | 0.5.11
| ~~system/library/python/libbe-39~~ | 0.5.11 | _Removed_
| **system/library/python/solaris-311** | _New_ | 0.5.11
| ~~system/library/python/solaris-39~~ | 0.5.11 | _Removed_
| **system/library/python/zfs-311** | _New_ | 0.5.11
| ~~system/library/python/zfs-39~~ | 0.5.11 | _Removed_
| **system/management/cloud-init** | _New_ | 23.1.1
| ~~system/management/ec2-credential~~ | 1.0 | _Removed_
| system/management/ipmitool | 1.8.18 | 1.8.19
| ~~system/network/http-cache-accelerator~~ | 0.5.11 | _Removed_
| system/pciutils | 3.7.0 | 3.9.0
| system/pciutils/pci.ids | 2.2.20211215 | 2.2.20230223
| system/rsyslog | 8.2102.0 | 8.2302.0
| system/test/fio | 3.26 | 3.34
| **system/test/smbsrvtest** | _New_ | 0.5.11
| ~~system/tnf~~ | 0.5.11 | _Removed_
| ~~system/virtualization/azure-agent~~ | 2.2.54 | _Removed_
| system/virtualization/open-vm-tools | 12.1.0 | 12.2.0
| terminal/screen | 4.8.0 | 4.9.0
| terminal/tmux | 3.1.3 | 3.3
| text/gawk | 5.1.0 | 5.2.1
| text/gnu-diffutils | 3.7 | 3.9
| text/gnu-gettext | 0.21 | 0.21.1
| text/gnu-grep | 3.6 | 3.10
| text/gnu-sed | 4.8 | 4.9
| text/less | 563 | 608
| web/wget | 1.21.1 | 1.21.3
| **web/wget2** | _New_ | 2.0.1

```[tasklist]
### Tasks
- [x] illumos-gate/master
- [x] helios-omnios-build - branched
- [x] helios-omnios-extra - branched
- [x] garbage compactor - branched
- [x] cockroach - upgraded, part of garbage-compactor branch
- [x] clickhouse
- [x] omicron
- [ ] IPS repository
- [x] propolis
- [x] crucible
- [x] dendrite - branched
- [x] opte
- [ ] maghemite
- [ ] CI image
- [ ] engvm
- [ ] helios-netdev CI
- [ ] helios-serdev?
- [x] heliosv1 -> heliosv2 pkg update process
- [ ] Update butlers
- [ ] Update build machines
- [ ] helios gimlet image
- [ ] illumos-gate/stlouis
```
